// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnegqudeykgsybckmacc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZWdxdWRleWtnc3liY2ttYWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzk4MTQsImV4cCI6MjA3MDk1NTgxNH0.buoUyM4JKYVrgwr1vjNU1_E5eqtK-DctUCr_B1uTWpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});